# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               mogli
tagline:             coding for fun
url:                 http://blog.mogli.me
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Remo Regli
  url:               http://blog.mogli.me
  email:             dev@mogli.me

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/moglich

# Create navigation bar
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
